[build]
  publish = "dashboard"
  command = "echo 'No build step required'"

[[redirects]]
  from = "/api/*"
  to = "https://shanon-web3-production.up.railway.app/api/:splat"
  status = 200
  force = true
